---
# file: 1_1_configure_cluster_members.yml

- hosts: hadoop
  become: yes
  become_user: root 

  vars_prompt:
    - name: "is_ssh_root_login"
      prompt: "Due to security concerns, it is encouraged to turn off remote root login via SSH. Do you want to turn it off (y/n)?"
      private: no
    - name: "use_auto_hosts_file"
      prompt: "Use automatic hosts file configuration based on group_vars/all network_prefix variable. This will automatically search for the FQDNs and IPs of all the hosts involved in the playbook and add them to the hosts file of every cluster-member. otherwise you have to configure the hosts files of every node yourself (y/n)?"
      private: no
    - name: "network_prefix_check"
      prompt: "The network_prefix variable in group_vars/all of this playbook is used to configure the hosts file of each cluster-member. Did you check the network_prefix variable to correspond to your cluster's internal network (y/n)?"
      private: no
      default: y
      when: use_auto_hosts_file == 'y' or use_auto_hosts_file == 'Y'
  
  tasks:
  - include_role:
      name: cluster-member
    vars:
      let_root_sshlogin: "{{ is_ssh_root_login }}"
    when: network_prefix_check == 'y' or network_prefix_check == 'Y'

...
