---
# file: 1_2_install_java.yml

- hosts: all
  become: yes
  become_user: root

  vars_prompt:
    - name: "jdk_agreement"
      prompt: "Did you check the jdk_url variable inside (roles/java/vars/main.yml)? Or, if you modified this playbook for manual java installation, did you placed your jdk.rpm file in /roles/java/files (y/n)?"
      private: no
  
  tasks:
  - include_role:
      name: java
    when: jdk_agreement == 'y' or jdk_agreement == 'Y'

...
