---
# Configures some aspects mainly related to security (e.g., http secret for SPNEGO). Execute after ambari installation, and any ambari configs should be done manually.
# File: 2_post_ambari_installation.yml

- hosts: hadoop
  become: yes
  become_user: root
  
  tasks:
  
    - name: generate http secret
      command: dd if=/dev/urandom of=/etc/security/http_secret bs=1024 count=1
    
    - name: change owner and permissions
      file:
        path: /etc/security/http_secret
        owner: hdfs
        group: hadoop
        mode: 0440
        
...