---
# file /roles/templates/ambariagent/tasks/main.yml

- name: download ambari repo
  get_url:
    url: "{{ ambari_repo_url }}"
    dest: /etc/yum.repos.d/ambari.repo
  
- name: yum install ambari agent
  yum:
    name: ambari-agent
    state: latest
    disable_gpg_check: yes

- name: create ambari user
  user:
    name: ambari
    home: /home/ambari
    system: yes

- name: change ambari-agent configurations
  lineinfile:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "{{ item.r }}"
    line: "{{ item.l }}"
  loop:
    - {r: "^hostname=", l: "hostname={{ groups['ambari-servers'][0] }}"}
    - {r: "^run_as_user=", l: "run_as_user=ambari"}

- name: add ambari user permissions to sudoers
  lineinfile:
    path: /etc/sudoers
    regexp: "{{ item.r }}"
    line: "{{ item.l }}"
  loop:
    - { r: '^ambari ALL=\(ALL\) NOPASSWD\:SETENV\: \/bin\/su hdfs', l: "ambari ALL=(ALL) NOPASSWD:SETENV: /bin/su hdfs *,/bin/su ambari-qa *,/bin/su ranger *,/bin/su zookeeper *,/bin/su knox *,/bin/su falcon *,/bin/su ams *, /bin/su flume *,/bin/su hbase *,/bin/su spark *,/bin/su accumulo *,/bin/su hive *,/bin/su hcat *,/bin/su kafka *,/bin/su mapred *,/bin/su oozie *,/bin/su sqoop *,/bin/su storm *,/bin/su tez *,/bin/su atlas *,/bin/su yarn *,/bin/su kms *,/bin/su activity_analyzer *,/bin/su livy *,/bin/su zeppelin *,/bin/su infra-solr *,/bin/su logsearch *" }
    - { r: '^ambari ALL=\(ALL\) NOPASSWD\:SETENV\: \/usr\/bin\/yum', l: "ambari ALL=(ALL) NOPASSWD:SETENV: /usr/bin/yum,/usr/bin/zypper,/usr/bin/apt-get, /bin/mkdir, /usr/bin/test, /bin/ln, /bin/ls, /bin/chown, /bin/chmod, /bin/chgrp, /bin/cp, /usr/sbin/setenforce, /usr/bin/test, /usr/bin/stat, /bin/mv, /bin/sed, /bin/rm, /bin/kill, /bin/readlink, /usr/bin/pgrep, /bin/cat, /usr/bin/unzip, /bin/tar, /usr/bin/tee, /bin/touch, /usr/bin/mysql, /sbin/service mysqld *, /usr/bin/dpkg *, /bin/rpm *, /usr/sbin/hst *, /sbin/service rpcbind *, /sbin/service portmap *" }
    - { r: '^ambari ALL=\(ALL\) NOPASSWD\:SETENV\: \/usr\/bin\/hdp-select', l: "ambari ALL=(ALL) NOPASSWD:SETENV: /usr/bin/hdp-select, /usr/bin/conf-select, /usr/hdp/current/hadoop-client/sbin/hadoop-daemon.sh, /usr/lib/hadoop/bin/hadoop-daemon.sh, /usr/lib/hadoop/sbin/hadoop-daemon.sh, /usr/bin/ambari-python-wrap *" }
    - { r: '^ambari ALL=\(ALL\) NOPASSWD\:SETENV\: \/usr\/sbin\/groupadd', l: "ambari ALL=(ALL) NOPASSWD:SETENV: /usr/sbin/groupadd, /usr/sbin/groupmod, /usr/sbin/useradd, /usr/sbin/usermod" }
    - { r: '^ambari ALL=\(ALL\) NOPASSWD\:SETENV\: \/usr\/bin\/python2\.6', l: "ambari ALL=(ALL) NOPASSWD:SETENV: /usr/bin/python2.6 /var/lib/ambari-agent/data/tmp/validateKnoxStatus.py *, /usr/hdp/current/knox-server/bin/knoxcli.sh" }
    - { r: '^ambari ALL=\(ALL\) NOPASSWD\:SETENV\: \/usr\/hdp\/\*\/ranger\-usersync\/setup\.sh', l: "ambari ALL=(ALL) NOPASSWD:SETENV: /usr/hdp/*/ranger-usersync/setup.sh, /usr/bin/ranger-usersync-stop, /usr/bin/ranger-usersync-start, /usr/hdp/*/ranger-admin/setup.sh *, /usr/hdp/*/ranger-knox-plugin/disable-knox-plugin.sh *, /usr/hdp/*/ranger-storm-plugin/disable-storm-plugin.sh *, /usr/hdp/*/ranger-hbase-plugin/disable-hbase-plugin.sh *, /usr/hdp/*/ranger-hdfs-plugin/disable-hdfs-plugin.sh *, /usr/hdp/current/ranger-admin/ranger_credential_helper.py, /usr/hdp/current/ranger-kms/ranger_credential_helper.py, /usr/hdp/*/ranger-*/ranger_credential_helper.py" }
    - { r: '^ambari ALL=\(ALL\) NOPASSWD\:SETENV\: \/usr\/lib\/ambari\-infra\-solr\/bin\/solr', l: "ambari ALL=(ALL) NOPASSWD:SETENV: /usr/lib/ambari-infra-solr/bin/solr *, /usr/lib/ambari-logsearch-logfeeder/run.sh *, /usr/sbin/ambari-metrics-grafana *, /usr/lib/ambari-infra-solr-client/solrCloudCli.sh *" }

- name: change some sudoers default configurations
  lineinfile:
    path: /etc/sudoers
    regexp: "{{ item }}"
    line: "{{ item }}"
  loop:
    - "Defaults exempt_group = ambari"
    - "Defaults !env_reset,env_delete-=PATH"
    - "Defaults: ambari !requiretty"
  
- name: ambari-agent start
  command: ambari-agent start

...