---
# file: /roles/java/tasks/main.yml
# from java 1.8.161 forward we don't need to configure JCE policies

# this role downloads the JDK directly from the web, but accessing older versions (sometimes required for Hadoop to work properly) sometimes requires Oracle login, 
# which makes the processes significantly difficult. Use this task if you want to install your jdk manually. You need to place the .rpm file for linux inside the
# files folder of this role 

#- name: copy local java rpm
#  copy:
#    src: "{{ item }}"
#    dest: "{{ ansible_env.HOME }}/jdk.rpm"
#  with_fileglob:
#    - "../files/*.rpm"

- name: download jdk
  get_url:
    url: "{{ jdk_url }}"
    dest: "{{ ansible_env.HOME }}/jdk.rpm"
    mode: 0700
    force: yes
    headers:
      Cookie: oraclelicense=accept-securebackup-cookie
      
- name: yum install java rpm
  yum:
    name: "{{ ansible_env.HOME }}/jdk.rpm"
    state: present
  register: result
  until: result.rc == 0
  retries: 3
  delay: 5
    
- name: remove java rpm
  file:
    path: "{{ ansible_env.HOME }}/jdk.rpm"
    state: absent

- name: send java.sh template to host
  template:
    src: "../templates/java.sh.j2"
    dest: "/etc/profile.d/java.sh"
    mode: 0755
    
- name: source java.sh
  shell: source /etc/profile.d/java.sh
    
- name: set alternatives
  alternatives:
    name: "{{ item }}"
    link: /usr/bin/{{ item }}
    path: "/usr/java/latest/bin/{{ item }}"
  loop:
    - java
    - javac
    - javaws
    - javadoc
    - jar

...
